### ISSUE TITLE
ドロップ処理を最適化する

### ISSUE THREAD

**Issue by yuki256R** [Project-C2/Project.C2#14]
ドロップ時の処理を全部functionに移行する軽量化を @nea-c がやる。

**Comment by nea-c** [comment]
1~30まで対応。
続きはまたやります。

**Comment by nea-c** [comment]
~現状の最後まで対応。
-121 17 -122のリピートコマンドブロックの中身を
「function project-c:general/itemdropping」に置き換えてください。

**Comment by nea-c** [comment]
94番の記述忘れ、..0のリセットをするように変更します。
